version: 2
updates:
- package-ecosystem: docker
  directory: "/happyhour"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/happyhour/rootfs/opt/happyhour"
  schedule:
    interval: daily
