---
name: HappyHour
version: dev
slug: happyhour
description: A HappyHour add-on for Home Assistant
url: https://github.com/filii-lamberti/addon-happyhour
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
hassio_api: true
homeassistant_api: true
ports:
  3000/tcp: 8214
options:
schema:
  logging: bool?
  debugging: bool?
image: ghcr.io/filii-lamberti/happyhour/{arch}